version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
    - epub

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/runtime.txt

sphinx:
  builder: html
  configuration: docs/zh_cn/conf.py
